Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,29 +17,25 @@ jobs:
           pip install -r requirements.txt
           python manage.py test taskManager
 
-  oast:
+  oast-frontend:
     machine: true
     steps:
       - checkout
-      - run: |
-          cat > .safety-policy.yml <<EOF
-          security:
-            ignore-vulnerabilities: {}
-          EOF
-      - run: docker run -v $(pwd):/src --rm hysnsec/safety check -r /src/requirements.txt --json | tee oast-results.json || true
+
+      - run:
+          name: Install npm packages
+          command: npm install
+
+      - run:
+          name: Run RetireJS
+          command: |
+            docker run --rm -v $(pwd):/src -w /src hysnsec/retire --outputformat json --outputpath retirejs-output.json --severity high || true
+
       - store_artifacts:
-          path: oast-results.json
-          destination: safety-artifact
-          
-  release:
-    machine: true                                        # What is this for?
-    steps:
-      - checkout
-      - run: |
-          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
-          docker build -t $DOCKER_USERNAME/django.nv .   # Build the application into Docker image
-          docker push $DOCKER_USERNAME/django.nv         # Push the image into registry
-          
+          path: retirejs-output.json
+          destination: retirejs-artifact
+          when: always
+
   integration:
     docker:
       - image: python:3.6
@@ -49,14 +45,14 @@ jobs:
           command: |
             echo "This is an integration step"
             exit 1
-          when: on_fail                   # Even if the job fails, continue to the next stages
+          when: on_fail         # Even if the job fails, continue to the next stages
 
   prod:
     docker:
       - image: python:3.6
     steps:
       - checkout
-      - run: echo "This is a 'deploy' step."
+      - run: echo "This is a deploy step."
 
 workflows:
   version: 2
@@ -66,15 +62,12 @@ workflows:
       - test:
           requires:
             - build
-      - oast:
+      - oast-frontend:
           requires:
             - test
-      - release:
-          requires:
-            - oast
       - integration:
           requires:
-            - release
+            - oast-frontend
       - prod:
           type: approval
           requires:
